# Generated by Django 3.2.6 on 2021-08-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
