# Generated by Django 3.2.6 on 2021-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
